### ISSUE TITLE
donwloadmq role: Specifying a version to download does not work

### ISSUE THREAD

**Issue by marianavillarp** [ibm-messaging/mq-ansible#82]
**Describe the bug**
When specifying a MQ version to install with downloadmq, this variable seems to be overriden by the default and installs 9.3.0

**To Reproduce**
In a playbook, using the collection downloaded from galaxy, specify the role to use with its variable:

```
 roles:
    - role: downloadmq
      vars:
        version: 933
        downloadURL: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/ 
```

**Expected behaviour**
The desired version of mq to be downloaded and installed

**Tell us the platform and version of the machine that ansible is being run on:**
 - OS: macOS Sonoma 14.1.1

**Tell us the version of ansible being used:**
 - ansible [core 2.15.6]

**Tell us the platforms and versions of the machines that the playbook is targetting (Usually supplied in an inventory file):**
 - OS: Ubuntu 22
